name: toktik_200525
description: A new Flutter project.
publish_to: 'none' # Este valor está bien para un proyecto privado.

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  intl: ^0.18.0
  provider: ^6.0.5
  video_player: ^2.5.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"  # Ruta a tu ícono

flutter:
  uses-material-design: true

  assets:
    - assets/videos/
    - assets/images/
